target_base_currency_market:
  - USDT
  - ETH
baseCurrency:
- BTC
- USDT
- ETH
BTC:
- BTC-LTC
- BTC-DOGE
- BTC-VTC
- BTC-PPC
- BTC-FTC
- BTC-RDD
- BTC-NXT
- BTC-DASH
- BTC-POT
- BTC-BLK
- BTC-EMC2
- BTC-XMY
- BTC-AUR
- BTC-EFL
- BTC-GLD
- BTC-SLR
- BTC-PTC
- BTC-GRS
- BTC-NLG
- BTC-RBY
- BTC-XWC
- BTC-MONA
- BTC-THC
- BTC-ENRG
- BTC-ERC
- BTC-VRC
- BTC-CURE
- BTC-XMR
- BTC-CLOAK
- BTC-START
- BTC-KORE
- BTC-XDN
- BTC-TRUST
- BTC-NAV
- BTC-XST
- BTC-VIA
- BTC-PINK
- BTC-IOC
- BTC-CANN
- BTC-SYS
- BTC-NEOS
- BTC-DGB
- BTC-BURST
- BTC-EXCL
- BTC-SWIFT
- BTC-DOPE
- BTC-BLOCK
- BTC-ABY
- BTC-BYC
- BTC-XMG
- BTC-BLITZ
- BTC-BAY
- BTC-FAIR
- BTC-SPR
- BTC-VTR
- BTC-XRP
- BTC-GAME
- BTC-COVAL
- BTC-NXS
- BTC-XCP
- BTC-BITB
- BTC-GEO
- BTC-FLDC
- BTC-GRC
- BTC-FLO
- BTC-NBT
- BTC-MUE
- BTC-XEM
- BTC-CLAM
- BTC-DMD
- BTC-GAM
- BTC-SPHR
- BTC-OK
- BTC-SNRG
- BTC-PKB
- BTC-AEON
- BTC-ETH
- BTC-TX
- BTC-BCY
- BTC-EXP
- BTC-OMNI
- BTC-AMP
- BTC-XLM
- BTC-CLUB
- BTC-RVR
- BTC-EMC
- BTC-FCT
- BTC-EGC
- BTC-SLS
- BTC-RADS
- BTC-DCR
- BTC-BSD
- BTC-XVG
- BTC-PIVX
- BTC-XVC
- BTC-MEME
- BTC-STEEM
- BTC-2GIVE
- BTC-LSK
- BTC-BRK
- BTC-WAVES
- BTC-LBC
- BTC-SBD
- BTC-BRX
- BTC-ETC
- BTC-STRAT
- BTC-UNB
- BTC-SYNX
- BTC-EBST
- BTC-VRM
- BTC-SEQ
- BTC-REP
- BTC-SHIFT
- BTC-ARDR
- BTC-XZC
- BTC-NEO
- BTC-ZEC
- BTC-ZCL
- BTC-IOP
- BTC-GOLOS
- BTC-UBQ
- BTC-KMD
- BTC-GBG
- BTC-SIB
- BTC-ION
- BTC-LMC
- BTC-QWARK
- BTC-CRW
- BTC-SWT
- BTC-MLN
- BTC-ARK
- BTC-DYN
- BTC-TKS
- BTC-MUSIC
- BTC-DTB
- BTC-INCNT
- BTC-GBYTE
- BTC-GNT
- BTC-NXC
- BTC-EDG
- BTC-LGD
- BTC-TRST
- BTC-WINGS
- BTC-RLC
- BTC-GNO
- BTC-GUP
- BTC-LUN
- BTC-HMQ
- BTC-ANT
- BTC-SC
- BTC-BAT
- BTC-ZEN
- BTC-QRL
- BTC-CRB
- BTC-PTOY
- BTC-CFI
- BTC-BNT
- BTC-NMR
- BTC-SNT
- BTC-DCT
- BTC-XEL
- BTC-MCO
- BTC-ADT
- BTC-PAY
- BTC-STORJ
- BTC-ADX
- BTC-OMG
- BTC-CVC
- BTC-PART
- BTC-QTUM
- BTC-BCC
- BTC-DNT
- BTC-ADA
- BTC-MANA
- BTC-SALT
- BTC-TIX
- BTC-RCN
- BTC-VIB
- BTC-MER
- BTC-POWR
- BTC-BTG
- BTC-ENG
- BTC-UKG
- BTC-IGNIS
- BTC-SRN
- BTC-WAX
- BTC-ZRX
- BTC-VEE
- BTC-BCPT
- BTC-TRX
- BTC-TUSD
- BTC-LRC
- BTC-UP
- BTC-DMT
ETH:
- ETH-ETC
- ETH-GNT
- ETH-REP
- ETH-WINGS
- ETH-GUP
- ETH-RLC
- ETH-LUN
- ETH-GNO
- ETH-HMQ
- ETH-TRST
- ETH-ANT
- ETH-BAT
- ETH-QRL
- ETH-CRB
- ETH-LGD
- ETH-PTOY
- ETH-CFI
- ETH-BNT
- ETH-NMR
- ETH-LTC
- ETH-XRP
- ETH-SNT
- ETH-MCO
- ETH-ADT
- ETH-PAY
- ETH-STORJ
- ETH-ADX
- ETH-DASH
- ETH-SC
- ETH-ZEC
- ETH-OMG
- ETH-CVC
- ETH-QTUM
- ETH-XMR
- ETH-XEM
- ETH-XLM
- ETH-NEO
- ETH-BCC
- ETH-DNT
- ETH-WAVES
- ETH-STRAT
- ETH-DGB
- ETH-FCT
- ETH-MANA
- ETH-SALT
- ETH-TIX
- ETH-RCN
- ETH-VIB
- ETH-POWR
- ETH-BTG
- ETH-ADA
- ETH-ENG
- ETH-UKG
- ETH-SRN
- ETH-WAX
- ETH-ZRX
- ETH-VEE
- ETH-BCPT
- ETH-TRX
- ETH-LRC
- ETH-TUSD
- ETH-UP
- ETH-DMT
USDT:
- USDT-BTC
- USDT-ETH
- USDT-ZEC
- USDT-LTC
- USDT-ETC
- USDT-XRP
- USDT-XMR
- USDT-DASH
- USDT-BCC
- USDT-NEO
- USDT-OMG
- USDT-BTG
- USDT-ADA
- USDT-XVG
- USDT-NXT
- USDT-TUSD
